/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.lxisoft;

import org.slf4j.*;
import com.lxisoft.controller.BoardController;
import com.lxisoft.controller.GameInitController;
import com.lxisoft.controller.LadderController;
import com.lxisoft.controller.SnakeController;
import com.lxisoft.model.*;
import com.lxisoft.util.*;
import com.lxisoft.view.controller.*;

import java.io.FileInputStream;
import java.io.IOException;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.layout.VBox;
import javafx.scene.layout.Pane;
import javafx.stage.Stage;
import javafx.stage.StageStyle;

public class App extends Application{

    private static final Logger log = LoggerFactory.getLogger(BoardController.class);
    
    public void start(Stage stage) throws IOException {

		ViewController viewController = new ViewController();

        Pane root = viewController.loadMenu();

		Scene scene = new Scene(root , 900 , 600);

		stage.setScene(scene);

		stage.initStyle(StageStyle.UNDECORATED);
		stage.setResizable(false);

		stage.setTitle("Snake and Ladders");

		stage.show();
    }

}
